"""Updated filetree mode

Revision ID: 132864f011f
Revises: 49544d3f150
Create Date: 2015-08-16 13:03:43.592429

"""

# revision identifiers, used by Alembic.
revision = '132864f011f'
down_revision = '49544d3f150'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree', sa.Column('parent', sa.Unicode(length=1024), nullable=True))
    op.add_column('tree', sa.Column('path', sa.Unicode(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree', 'path')
    op.drop_column('tree', 'parent')
    op.add_column('file', sa.Column('server', sa.VARCHAR(length=1024), nullable=True))
    ### end Alembic commands ###
