"""Updated filetree mod

Revision ID: 142f72b0a38
Revises: 132864f011f
Create Date: 2015-08-16 13:20:08.319384

"""

# revision identifiers, used by Alembic.
revision = '142f72b0a38'
down_revision = '132864f011f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree', sa.Column('children', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('file', sa.Column('server', sa.VARCHAR(length=1024), nullable=True))
    ### end Alembic commands ###
