"""Added tree state

Revision ID: 1600866a2f5
Revises: 206921a85c4
Create Date: 2015-09-11 15:05:35.466586

"""

# revision identifiers, used by Alembic.
revision = '1600866a2f5'
down_revision = '206921a85c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree', sa.Column('state', sa.Unicode(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree', 'state')
    ### end Alembic commands ###
