"""Fix User Class

Revision ID: 1c57461688e
Revises: 249cce9da5c
Create Date: 2015-08-04 14:01:31.613508

"""

# revision identifiers, used by Alembic.
revision = '1c57461688e'
down_revision = '249cce9da5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filetree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Unicode(length=1024), nullable=True),
    sa.Column('localpath', sa.Unicode(length=1024), nullable=True),
    sa.Column('serverpath', sa.Unicode(length=1024), nullable=True),
    sa.Column('type', sa.Unicode(length=1024), nullable=True),
    sa.Column('text', sa.Unicode(length=1024), nullable=True),
    sa.Column('children', sa.Unicode(length=1024), nullable=True),
    sa.Column('icon', sa.Unicode(length=1024), nullable=True),
    sa.Column('path', sa.Unicode(length=1024), nullable=False),
    sa.Column('rel_path', sa.Unicode(length=1024), nullable=False),
    sa.Column('size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rel_path'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('path')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
