"""Fix User Class

Revision ID: 1c57461688e
Revises: 249cce9da5c
Create Date: 2015-08-04 14:01:31.613508

"""

# revision identifiers, used by Alembic.
revision = '1c57461688e'
down_revision = '249cce9da5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
