"""Added section to RegisteredTool

Revision ID: 1cd09004f3b
Revises: 71142fe391
Create Date: 2015-09-25 20:40:15.464132

"""

# revision identifiers, used by Alembic.
revision = '1cd09004f3b'
down_revision = '71142fe391'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registeredtool', sa.Column('section', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registeredtool', 'section')
    ### end Alembic commands ###
