"""Alter user_local with jca update

Revision ID: 1d7521b8be9
Revises: 1600866a2f5
Create Date: 2015-09-16 10:20:35.132034

"""

# revision identifiers, used by Alembic.
revision = '1d7521b8be9'
down_revision = '1600866a2f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
