"""Added user_local confirmation

Revision ID: 206921a85c4
Revises: 5a0ce8aef93
Create Date: 2015-09-11 14:47:27.014703

"""

# revision identifiers, used by Alembic.
revision = '206921a85c4'
down_revision = '5a0ce8aef93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('local_user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_user', 'confirmed_on')
    op.drop_column('local_user', 'confirmed')
    ### end Alembic commands ###
