"""Updated fileTree model

Revision ID: 2241919df5c
Revises: 4b6c10772b5
Create Date: 2015-08-16 11:48:42.200969

"""

# revision identifiers, used by Alembic.
revision = '2241919df5c'
down_revision = '4b6c10772b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
