"""4th_test

Revision ID: 2784ea9087a
Revises: 375df472bf1
Create Date: 2015-07-25 17:14:29.964636

"""

# revision identifiers, used by Alembic.
revision = '2784ea9087a'
down_revision = '375df472bf1'

from alembic import op
import sqlalchemy as sa
from server.models.models import JSONEncodedDict


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registeredtool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=1024), nullable=True),
    sa.Column('options', JSONEncodedDict(), nullable=True),
    sa.Column('help', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Unicode(length=1024), nullable=True),
    sa.Column('first_name', sa.Unicode(length=1024), nullable=True),
    sa.Column('last_name', sa.Unicode(length=1024), nullable=True),
    sa.Column('password', sa.Unicode(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Unicode(length=1024), nullable=True),
    sa.Column('localpath', sa.Unicode(length=1024), nullable=True),
    sa.Column('serverpath', sa.Unicode(length=1024), nullable=True),
    sa.Column('type', sa.Unicode(length=1024), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Unicode(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('localpath'),
    sa.UniqueConstraint('serverpath')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('args', sa.Unicode(length=1024), nullable=True),
    sa.Column('input_path', sa.Unicode(length=1024), nullable=True),
    sa.Column('output_path', sa.Unicode(length=1024), nullable=True),
    sa.Column('name', sa.Unicode(length=1024), nullable=True),
    sa.Column('file_id', sa.Unicode(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['name'], ['registeredtool.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_path'),
    sa.UniqueConstraint('output_path')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('file')
    op.drop_table('user')
    op.drop_table('registeredtool')
    ### end Alembic commands ###
