"""Updated filetree modell

Revision ID: 49544d3f150
Revises: 58ba8f7a3a3
Create Date: 2015-08-16 12:23:06.653410

"""

# revision identifiers, used by Alembic.
revision = '49544d3f150'
down_revision = '58ba8f7a3a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('server', sa.VARCHAR(length=1024), nullable=True))
    op.create_table('filetree',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.Column('rel_path', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('size', sa.FLOAT(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('type', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('children', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tree')
    ### end Alembic commands ###
