"""Updated file model

Revision ID: 4b6c10772b5
Revises: 1c57461688e
Create Date: 2015-08-16 11:46:35.858468

"""

# revision identifiers, used by Alembic.
revision = '4b6c10772b5'
down_revision = '1c57461688e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('children', sa.Unicode(length=1024), nullable=True))
    op.add_column('file', sa.Column('icon', sa.Unicode(length=1024), nullable=True))
    op.add_column('file', sa.Column('text', sa.Unicode(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'text')
    op.drop_column('file', 'icon')
    op.drop_column('file', 'children')
    ### end Alembic commands ###
