"""Updated filetree model

Revision ID: 58ba8f7a3a3
Revises: 2241919df5c
Create Date: 2015-08-16 12:19:56.811759

"""

# revision identifiers, used by Alembic.
revision = '58ba8f7a3a3'
down_revision = '2241919df5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('serverpath', sa.VARCHAR(length=1024), nullable=True))
    op.drop_column('file', 'server')
    op.drop_table('filetree')
    ### end Alembic commands ###
