"""Added user_local table

Revision ID: 5a0ce8aef93
Revises: 26b88e19ee9
Create Date: 2015-09-09 16:08:21.655787

"""

# revision identifiers, used by Alembic.
revision = '71142fe391'
down_revision = '26b88e19ee9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
