"""Updated filetree mo

Revision ID: 61ed55c59d
Revises: 142f72b0a38
Create Date: 2015-08-16 13:29:37.365359

"""

# revision identifiers, used by Alembic.
revision = '61ed55c59d'
down_revision = '142f72b0a38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree', sa.Column('children', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('tree', sa.Column('path', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('file', sa.Column('server', sa.VARCHAR(length=1024), nullable=True))
    ### end Alembic commands ###
