"""Added deleted for tree files

Revision ID: 662943ea58
Revises: 1cd09004f3b
Create Date: 2015-10-01 08:42:40.000720

"""

# revision identifiers, used by Alembic.
revision = '662943ea58'
down_revision = '1cd09004f3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree', sa.Column('deleted', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree', 'deleted')
    ### end Alembic commands ###
