"""Alter user_local with jca update v2

Revision ID: 71142fe391
Revises: 1d7521b8be9
Create Date: 2015-09-16 10:23:33.325465

"""

# revision identifiers, used by Alembic.
revision = '71142fe391'
down_revision = '1d7521b8be9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
