"""initial

Revision ID: 3471bfe298
Revises: None
Create Date: 2015-06-17 13:53:43.039304

"""

# revision identifiers, used by Alembic.
revision = '3471bfe298'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.password import PasswordType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('expire_on', sa.DateTime(), nullable=False),
    sa.Column('command_id', sa.Unicode(length=36), nullable=True),
    sa.Column('command_type', sa.Unicode(length=1024), nullable=True),
    sa.Column('command_date', sa.UnicodeText(), nullable=True),
    sa.Column('identity', sa.Unicode(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Unicode(length=1024), nullable=True),
    sa.Column('first_name', sa.Unicode(length=1024), nullable=True),
    sa.Column('last_name', sa.Unicode(length=1024), nullable=True),
    sa.Column('password', PasswordType(max_length=1137), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('command')
    ### end Alembic commands ###
