"""initial

Revision ID: 1d431b7aa6f
Revises: None
Create Date: 2015-07-24 23:31:40.409635

"""

# revision identifiers, used by Alembic.
revision = '1d431b7aa6f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('command')
    ### end Alembic commands ###
