"""first

Revision ID: 231fbe028d5
Revises: 1d431b7aa6f
Create Date: 2015-07-25 17:07:46.059658

"""

# revision identifiers, used by Alembic.
revision = '231fbe028d5'
down_revision = '1d431b7aa6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.Column('expire_on', sa.DATETIME(), nullable=False),
    sa.Column('command_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('command_type', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('command_date', sa.TEXT(), nullable=True),
    sa.Column('identity', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id')
    )
    ### end Alembic commands ###
