"""5th

Revision ID: 249cce9da5c
Revises: 2784ea9087a
Create Date: 2015-07-25 17:16:36.378890

"""

# revision identifiers, used by Alembic.
revision = '249cce9da5c'
down_revision = '2784ea9087a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
