"""third

Revision ID: 375df472bf1
Revises: 40dc90b7aee
Create Date: 2015-07-25 17:12:52.917126

"""

# revision identifiers, used by Alembic.
revision = '375df472bf1'
down_revision = '40dc90b7aee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
