"""second

Revision ID: 40dc90b7aee
Revises: 231fbe028d5
Create Date: 2015-07-25 17:09:37.123186

"""

# revision identifiers, used by Alembic.
revision = '40dc90b7aee'
down_revision = '231fbe028d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
